kind = "web"
previewPath = "/"
title = "Lonely Bypass"
version = "1.0.0"
id = "artifacts/lonely-bypass"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19408

[services.development]
run = "pnpm --filter @workspace/lonely-bypass run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/lonely-bypass", "run", "build" ]
publicDir = "artifacts/lonely-bypass/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19408"
BASE_PATH = "/"
